# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: "Mortyran's homepage"
    twitter: 'MortyRan'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Dec 5, 2022'
  time_format: '12:00 AM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_lighttheme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/mortyran/HomePage'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true

# Background
# design:
#   background:
#     # Name of image in `assets/media/`.
#     image: background.png
#     # Darken the image? Range 0-1 where 0 is transparent and 1 is opaque.
#     image_darken: 0.6
#     #  Options are `cover` (default), `contain`, or `actual` size.
#     image_size: cover
#     # Options include `left`, `center` (default), or `right`.
#     image_position: center
#     # Use a fun parallax-like fixed background effect on desktop? true/false
#     image_parallax: true
#     # Text color (true=light, false=dark, or remove for the dynamic theme color).
#     text_color_light: true

design:
  background:
    # Choose a color such as from https://html-color-codes.info
    color: '＃90EE90'
    # Text color (true=light, false=dark, or remove for the dynamic theme color). 
    text_color_light: true
